export const DIVISAS = [
  { code: 'EUR', label: 'EUR - EURO', symbol: '€', decimal: ',', separator: '.' },
  { code: 'USD', label: 'USD - DÓLAR AMERICANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'GBP', label: 'GBP - LIBRA ESTERLINA', symbol: '£', decimal: '.', separator: ',' },
  { code: 'JPY', label: 'JPY - YEN JAPONÉS', symbol: '¥', decimal: '.', separator: ',', precision: 0 },
  { code: 'CHF', label: 'CHF - FRANCO SUIZO', symbol: 'CHF ', decimal: '.', separator: "'" },
  { code: 'CAD', label: 'CAD - DÓLAR CANADIENSE', symbol: 'CA$', decimal: '.', separator: ',' },
  { code: 'AUD', label: 'AUD - DÓLAR AUSTRALIANO', symbol: 'A$', decimal: '.', separator: ',' },
  { code: 'MXN', label: 'MXN - PESO MEXICANO', symbol: '$', decimal: '.', separator: ',' },
  { code: 'BRL', label: 'BRL - REAL BRASILEÑO', symbol: 'R$', decimal: ',', separator: '.' },
  { code: 'ARS', label: 'ARS - PESO ARGENTINO', symbol: '$', decimal: ',', separator: '.' },
  { code: 'COP', label: 'COP - PESO COLOMBIANO', symbol: '$', decimal: ',', separator: '.' },
  { code: 'CLP', label: 'CLP - PESO CHILENO', symbol: '$', decimal: ',', separator: '.', precision: 0 },
  { code: 'PEN', label: 'PEN - SOL PERUANO', symbol: 'S/', decimal: '.', separator: ',' },
  { code: 'DKK', label: 'DKK - CORONA DANESA', symbol: 'kr', decimal: ',', separator: '.' },
  { code: 'SEK', label: 'SEK - CORONA SUECA', symbol: 'kr', decimal: ',', separator: '.' },
  { code: 'NOK', label: 'NOK - CORONA NORUEGA', symbol: 'kr', decimal: ',', separator: '.' },
  { code: 'PLN', label: 'PLN - ESLOTI POLACO', symbol: 'zł', decimal: ',', separator: '.' },
  { code: 'CZK', label: 'CZK - CORONA CHECA', symbol: 'Kč', decimal: ',', separator: '.' },
  { code: 'HUF', label: 'HUF - FORINTO HÚNGARO', symbol: 'Ft', decimal: ',', separator: '.', precision: 0 },
  { code: 'TRY', label: 'TRY - LIRA TURCA', symbol: '₺', decimal: ',', separator: '.' },
  { code: 'AED', label: 'AED - DÍRHAM EMIRATÍ', symbol: 'د.إ', decimal: '.', separator: ',' },
  { code: 'THB', label: 'THB - BAHT TAILANDÉS', symbol: '฿', decimal: '.', separator: ',' },
  { code: 'SGD', label: 'SGD - DÓLAR DE SINGAPUR', symbol: 'S$', decimal: '.', separator: ',' },
  { code: 'HKD', label: 'HKD - DÓLAR DE HONG KONG', symbol: 'HK$', decimal: '.', separator: ',' },
  { code: 'KRW', label: 'KRW - WON SURCOREANO', symbol: '₩', decimal: '.', separator: ',', precision: 0 },
  { code: 'INR', label: 'INR - RUPIA INDIA', symbol: '₹', decimal: '.', separator: ',' },
  { code: 'ZAR', label: 'ZAR - RAND SUDAFRICANO', symbol: 'R', decimal: '.', separator: ',' },
  { code: 'MAD', label: 'MAD - DÍRHAM MARROQUÍ', symbol: 'MAD', decimal: '.', separator: ',' },
];
